### get inital values

GET http://localhost:3001/tweets/1

### post new tweet

POST http://localhost:3001/tweets
Content-Type: application/json

{
  "userId": 1,
  "tweet": "test content returning all tweet"
}