### get inital values

GET http://localhost:3001/tweets/all/1

### post new tweet

POST http://localhost:3001/tweets
Content-Type: application/json

{
  "userId": 1,
  "tweet": "test content returning all tweet 3"
}

### delete tweet

DELETE http://localhost:3001/tweets/50

### update tweet

PUT http://localhost:3001/tweets/49
Content-Type: application/json

{
  "tweet": "updating tweet number 49"
}