### get inital values

GET http://localhost:3001/tweets/all/1

### post new tweet

POST http://localhost:3001/tweets
Content-Type: application/json

{
  "userId": 1,
  "tweet": "some interesting things going on"
}

### delete tweet

DELETE http://localhost:3001/tweets/50

### update tweet

PUT http://localhost:3001/tweets/49
Content-Type: application/json

{
  "tweet": "updating tweet number 49"
}

### get comments

GET http://localhost:3001/comments/?tweetId=49

### post new comment

POST http://localhost:3001/comments
Content-Type: application/json

{
  "userId": 1,
  "tweetId": 49,
  "content": "some comment for tweet 49"
}

### update comment

PUT http://localhost:3001/comments/2
Content-Type: application/json

{
  "content": "updating the second comment"
}

### delete comment

DELETE http://localhost:3001/comments/2

### add like

POST http://localhost:3001/likes
Content-Type: application/json

{
  "userId": 1,
  "tweetId": 1
}

### remove like

DELETE http://localhost:3001/likes
Content-Type: application/json

{
  "userId": 1,
  "tweetId": 1
}